### ISSUE TITLE
Grails 3.3.4 Boot Issue

### ISSUE THREAD

**Issue by ali-mansoor** [grails3-plugins/mail#33]
Grails 3.3.4
Plugin   compile "org.grails.plugins:mail:2.0.0"

Getting exception on Boot

Caused by: java.lang.NoClassDefFoundError: grails/plugins/mail/SendMail

**Comment by erichelgeson** [comment]
Closing due to age (and it does work in 3.3.x) - Please re-open if you can provide a full example. Apologies for the late reply.
